// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "TopNav": { "restaurants": "Restaurants", "reservations": "Reservations" },
  "HomePage": { "title": "Restaurant Reservation", "greeting": "Hello {username}" },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, th {🇹🇭 ไทย} en {🇺🇸 English} other {Unknown}}"
  }
};
export default messages;